User.create!(username: "alice", password: "wonderland")
User.create!(username: "bob",   password: "asdfasdf")


Dialect.create!(name: "none (use for debugging)")
Dialect.create!(name: "Yoda")
Dialect.create!(name: "ROT13 (explanation)")
Dialect.create!(name: "All your base are belong to us")
Dialect.create!(name: "Boston accent")
Dialect.create!(name: "Canadian")
Dialect.create!(name: "simple hax0r")
Dialect.create!(name: "Ali G")
Dialect.create!(name: "Valley Girl")
Dialect.create!(name: "Binary (messy)")
Dialect.create!(name: "Jeff K (if you don't understand, don't ask)")
Dialect.create!(name: "Ultra Leet")
Dialect.create!(name: "Martian")
Dialect.create!(name: "Pig Latin")
Dialect.create!(name: "Smurf")
